defaults:
  - agent: ddpg
  - skill_selector: sac
  - override hydra/launcher: submitit_local

# mode
reward_free: false
# task settings
task: walker_stand
domain: walker
obs_type: states # [states, pixels]
frame_stack: 3 # only works if obs_type=pixels
action_repeat: 1 # set to 2 for pixels
discount: 0.99
# train settings
num_train_frames: 100010
num_seed_frames: 4000
# eval
eval_every_frames: 10000
num_eval_episodes: 10
# pretrained
snapshot_ts: 2000000
snapshot_base_dir: ./models
# replay buffer
replay_buffer_size: 1000000
replay_buffer_num_workers: 4
batch_size: ${agent.batch_size}
nstep: ${agent.nstep}
update_encoder: false # can be either true or false depending if we want to fine-tune encoder
# misc
seed: 1
device: cuda
save_video: false
save_train_video: false
use_tb: false
use_wandb: true
# define specific path for experiment
wandb_key: a8427ff652cae08031aad508e6c421e3e513d814
experiment: ${agent.name}_seed_${seed}
extra_path: .

hydra:
  run:
    dir: ./exp_local/finetune_${extra_path}/${domain}/${agent.name}/fintune_${experiment}_${task}_${now:%H%M%S}
  sweep:
    dir: ./exp_local/finetune_${extra_path}/${domain}/${agent.name}/fintune_${experiment}_${task}_${now:%H%M%S}
    subdir: ${hydra.job.num}
  launcher:
    timeout_min: 4300
    cpus_per_task: 10
    gpus_per_node: 1
    tasks_per_node: 1
    mem_gb: 160
    nodes: 1
    submitit_folder: ./exp_sweep/${now:%Y.%m.%d}/${now:%H%M}_${agent.name}_${experiment}/.slurm
