# @package skill_selector
_target_: skill_selector.sac_rnn.SACRNNSkillSelector
obs_shape: ???  # to be specified later
skill_dim: 16
device: ${device}
lr: 1e-4
hidden_dim: 512
update_every_steps: 25
alpha: 0.1   # entropy coefficient
gamma: 0.995
tau: 0.005  # target network update rate