# @package skill_selector
_target_: skill_selector.sac_rnn.SACRNNSkillSelector
obs_shape: ???  # to be specified later
skill_dim: 16
device: ${device}
lr: 3e-4
hidden_dim: 256
update_every_steps: 50
alpha: 0.2  # entropy coefficient
gamma: 0.99
tau: 0.005  # target network update rate