# @package agent
_target_: agent.amped.AmpedAgent
name: amped
reward_free: ${reward_free}
obs_type: ??? # to be specified later
obs_shape: ??? # to be specified later
action_shape: ??? # to be specified later
device: ${device}
lr: 1e-4
critic_target_tau: 0.01
update_every_steps: 2
use_tb: ${use_tb}
use_wandb: ${use_wandb}
num_expl_steps: 2000 # to be specified later
hidden_dim: 1024
feature_dim: 50
stddev_schedule: 0.2
stddev_clip: 0.3
skill_dim: 16
update_skill_every_step: 50
nstep: 3
batch_size: 1024
init_critic: true
update_encoder: ${update_encoder}

# extra hyperparameter
contrastive_update_rate: 3
temperature: 0.5
alpha: 0.01
beta: 10
update_rep: true
project_skill: true

# becl hyperparameter
becl_cic_ratio: 0.8 # range: [0.0, 1.0], if 1.0 cic is much more important than becl

# skill finetuning ablation
skill: -1
